// Generated by CMakeLists.txt. Do not edit.
#ifndef BASE_VERSION_INFO_VERSION_INFO_VALUES_H_
#define BASE_VERSION_INFO_VERSION_INFO_VALUES_H_

// Stub values for the CMake minimal build of libbase.a.
// Upstream these are produced by //build/util/process_version.gni at GN time.
#define PRODUCT_NAME "Chromium"
#define PRODUCT_VERSION "0.0.0.0"
#define LAST_CHANGE "0"
#define IS_OFFICIAL_BUILD false

#endif  // BASE_VERSION_INFO_VERSION_INFO_VALUES_H_
