// Generated by CMakeLists.txt. Do not edit.
#ifndef BASE_CFI_BUILDFLAGS_H_
#define BASE_CFI_BUILDFLAGS_H_

#include "build/buildflag.h"

#define BUILDFLAG_INTERNAL_CFI_CAST_CHECK() (false)
#define BUILDFLAG_INTERNAL_CFI_DIAG() (false)
#define BUILDFLAG_INTERNAL_CFI_ICALL_CHECK() (false)
#define BUILDFLAG_INTERNAL_CFI_ENFORCEMENT_TRAP() (false)
#define BUILDFLAG_INTERNAL_CFI_ENFORCEMENT_DIAGNOSTIC() (false)

#endif  // BASE_CFI_BUILDFLAGS_H_
