// Generated by CMakeLists.txt. Do not edit.
#ifndef BASE_FEATURE_LIST_BUILDFLAGS_H_
#define BASE_FEATURE_LIST_BUILDFLAGS_H_

#include "build/buildflag.h"

#define BUILDFLAG_INTERNAL_ENABLE_BANNED_BASE_FEATURE_PREFIX() (false)

#endif  // BASE_FEATURE_LIST_BUILDFLAGS_H_
