// Generated by CMakeLists.txt. Do not edit.
#ifndef BASE_FUZZING_BUILDFLAGS_H_
#define BASE_FUZZING_BUILDFLAGS_H_

#include "build/buildflag.h"

#define BUILDFLAG_INTERNAL_USE_FUZZING_ENGINE() (false)

#endif  // BASE_FUZZING_BUILDFLAGS_H_
