// Generated by CMakeLists.txt. Do not edit.
#ifndef BASE_LOGGING_BUILDFLAGS_H_
#define BASE_LOGGING_BUILDFLAGS_H_

#include "build/buildflag.h"

#define BUILDFLAG_INTERNAL_ENABLE_LOG_ERROR_NOT_REACHED() (true)

#endif  // BASE_LOGGING_BUILDFLAGS_H_
