// Generated by CMakeLists.txt. Do not edit.
#ifndef BASE_RUST_BUILDFLAGS_H_
#define BASE_RUST_BUILDFLAGS_H_

#include "build/buildflag.h"

#define BUILDFLAG_INTERNAL_BUILD_RUST_JSON_READER() (false)
#define BUILDFLAG_INTERNAL_BUILD_RUST_BASE_CONVERSIONS() (false)

#endif  // BASE_RUST_BUILDFLAGS_H_
