// Generated by CMakeLists.txt. Do not edit.
#ifndef BASE_SANITIZER_BUILDFLAGS_H_
#define BASE_SANITIZER_BUILDFLAGS_H_

#include "build/buildflag.h"

#define BUILDFLAG_INTERNAL_IS_HWASAN() (false)
#define BUILDFLAG_INTERNAL_USING_SANITIZER() (false)

#endif  // BASE_SANITIZER_BUILDFLAGS_H_
