// Generated by CMakeLists.txt. Do not edit.
#ifndef BASE_MESSAGE_LOOP_IOS_CRONET_BUILDFLAGS_H_
#define BASE_MESSAGE_LOOP_IOS_CRONET_BUILDFLAGS_H_

#include "build/buildflag.h"

#define BUILDFLAG_INTERNAL_CRONET_BUILD() (false)

#endif  // BASE_MESSAGE_LOOP_IOS_CRONET_BUILDFLAGS_H_
