// Generated by CMakeLists.txt. Do not edit.
#ifndef PARTITION_ALLOC_CHROMEOS_BUILDFLAGS_H_
#define PARTITION_ALLOC_CHROMEOS_BUILDFLAGS_H_

#include "build/buildflag.h"

#define BUILDFLAG_INTERNAL_PA_IS_CHROMEOS_ASH() (false)

#endif  // PARTITION_ALLOC_CHROMEOS_BUILDFLAGS_H_
