// Generated by CMakeLists.txt. Do not edit.
#ifndef PARTITION_ALLOC_RAW_PTR_BUILDFLAGS_H_
#define PARTITION_ALLOC_RAW_PTR_BUILDFLAGS_H_

#include "build/buildflag.h"

// Match the upstream defaults from
// //base/allocator/partition_allocator/build_overrides/partition_alloc.gni
// These are *required* when USE_PARTITION_ALLOC=false: with the no-op
// implementation the default ctor is `= default`, which means
// `const raw_ptr<T>` members cannot be default-initialized (C++ requires a
// user-provided default ctor). Enabling these flags makes the ctors
// user-provided and zeroes the wrapped pointer, matching Chromium's
// regular build behaviour.
#define BUILDFLAG_INTERNAL_RAW_PTR_ZERO_ON_CONSTRUCT() (true)
#define BUILDFLAG_INTERNAL_RAW_PTR_ZERO_ON_MOVE() (true)
#define BUILDFLAG_INTERNAL_RAW_PTR_ZERO_ON_DESTRUCT() (false)

#endif  // PARTITION_ALLOC_RAW_PTR_BUILDFLAGS_H_
