// Generated by CMakeLists.txt. Do not edit.
#ifndef BASE_WIN_BASE_WIN_BUILDFLAGS_H_
#define BASE_WIN_BASE_WIN_BUILDFLAGS_H_

#include "build/buildflag.h"

#define BUILDFLAG_INTERNAL_SINGLE_MODULE_MODE_HANDLE_VERIFIER() (false)
#define BUILDFLAG_INTERNAL_WIN_ENABLE_CFG_GUARDS() (false)

#endif  // BASE_WIN_BASE_WIN_BUILDFLAGS_H_
